# -*- coding: utf-8 -*-
channel 1.iltapulu.fi YLE TV1
channel 10.iltapulu.fi AVA
channel 11.iltapulu.fi Yle Teema & Fem
channel 13.iltapulu.fi Liv
channel 2.iltapulu.fi YLE TV2
channel 3.iltapulu.fi MTV3
channel 4.iltapulu.fi Nelonen
channel 5.iltapulu.fi TV5
channel 6.iltapulu.fi Sub
channel 62.iltapulu.fi Kutonen
channel 7.iltapulu.fi JIM
channel 73.iltapulu.fi Hero
channel 74.iltapulu.fi FRII
channel 8.iltapulu.fi STAR Channel
channel 81.iltapulu.fi TLC
channel 82.iltapulu.fi National Geographic
channel star-channel.ampparit.com STAR Channel